%dev.quarkus.http.port=8081
# 本番環境では環境変数PORTで指定。
%prod.quarkus.http.port=${PORT}

# DB schema
%dev.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
%test.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
%prod.quarkus.hibernate-orm.schema-management.strategy=create
%dev.quarkus.hibernate-orm.log.sql=true
%dev.quarkus.hibernate-orm.log.bind-parameters=true

# デフォルトでは、認証されていないエンドポイントへのアクセスを拒否する設定にする。
quarkus.security.jaxrs.deny-unannotated-endpoints=true

# JWT
mp.jwt.verify.issuer=https://sns.example.com
# Quarkusでは24hという簡略表記もできるが、Language Serverは理解できず問題として認識されるためISO 8601形式で書いておく。
app.jwt.token-validity=PT24H
# 開発環境ではdev-keysディレクトリから公開鍵と秘密鍵を読み込む。本番でこのキーを利用しないよう注意。
%dev.mp.jwt.verify.publickey.location=dev-keys/publicKey.pem
%test.mp.jwt.verify.publickey.location=dev-keys/publicKey.pem
%dev.smallrye.jwt.sign.key.location=dev-keys/privateKey.pem
%test.smallrye.jwt.sign.key.location=dev-keys/privateKey.pem
# 本番環境では環境変数で公開鍵と秘密鍵を指定。
%prod.mp.jwt.verify.publickey=${JWT_VERIFY_PUBLIC_KEY}
%prod.smallrye.jwt.sign.key=${JWT_SIGN_KEY}

# 本番環境での管理者の初期設定
%prod.app.initial-admin.username=${ADMIN_USERNAME:admin}
%prod.app.initial-admin.email=${ADMIN_EMAIL}
%prod.app.initial-admin.password=${ADMIN_PASSWORD}

# 本番環境では環境変数でデータベースを設定。
%prod.quarkus.datasource.jdbc.url=${DATABASE_URL}
%prod.quarkus.datasource.username=${DATABASE_USERNAME}
%prod.quarkus.datasource.password=${DATABASE_PASSWORD}

# Docker Hub へPushする場合は、Docker Hubのaccount nameをxxxxxxの部分に設定すること。
# quarkus.container-image.group=xxxxxx

%dev.quarkus.datasource.dev-ui.allow-sql=true
